### ISSUE TITLE
JEI not showing recipes on mod installation in dedicated servers

### ISSUE THREAD

**Issue by FelineEngineer** [Midknight-Maxielle/MK-Drinks#1]
Version 1.16.5-0.1.2.1 hides a majority of recipes from JEI. Modlist attached with mkdrinks made non-functional by changing the extension.
[list.txt](https://github.com/Midknight-Maxielle/MK-Drinks/files/7588748/list.txt)
.

**Comment by cryptidseabird** [comment]
Thanks again for reporting this - I've refactored the code and this should be solved in the latest update!
